Fix the HyperShift failure on the manifest
Take a failing job [1],

```console
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/logs/periodic-ci-openshift-hypershift-release-4.22-periodics-e2e-aks/2030738474943909888/artifacts/e2e-aks/hypershift-azure-run-e2e/artifacts/TestCreateCluster/namespaces/e2e-clusters-v6hh4-create-cluster-pcmgf/core/pods/logs/cluster-version-operator-7d8d59977-vrrvw-bootstrap.log | tail -n 6
  rolebinding.rbac.authorization.k8s.io/prometheus-k8s unchanged
  error: resource mapping not found for name: "cluster-version-operator-accept-risks" namespace: "openshift-cluster-version" from "/var/payload/manifests/0000_90_cluster-version-operator_02_prometheusrule-TechPreviewNoUpgrade.yaml": no matches for kind "PrometheusRule" in version "monitoring.coreos.com/v1"
  ensure CRDs are installed first
...
```

So we apply the manifest too early.

How come the existing manifest
`0000_90_cluster-version-operator_02_servicemonitor.yaml`
has no such an issue? It contains PrometheusRules as well [2].

The answer is here:

```console
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/logs/periodic-ci-openshift-hypershift-release-4.22-periodics-e2e-aks/2030738474943909888/artifacts/e2e-aks/hypershift-azure-run-e2e/artifacts/TestCreateCluster/namespaces/e2e-clusters-v6hh4-create-cluster-pcmgf/core/pods/cluster-version-operator-7d8d59977-vrrvw.yaml | yq -r '.spec.initContainers[]|select(.name=="prepare-payload").args[1]'
  cp -R /manifests /var/payload/
  rm -f /var/payload/manifests/*_deployment.yaml
  rm -f /var/payload/manifests/*_servicemonitor.yaml
  cp -R /release-manifests /var/payload/
  rm -f /var/payload/manifests/*-Default*.yaml
  rm -f /var/payload/manifests/*-CustomNoUpgrade*.yaml
  rm -f /var/payload/manifests/*-DevPreviewNoUpgrade*.yaml
  rm -f /var/payload/manifests/*-OKD*.yaml
  rm -f /var/payload/release-manifests/0000_50_olm_00-pprof-config.yaml
...
```

From the above command:

* The FeatureSet on the cluster is `TechPreviewNoUpgrade`. Otherwise, we
  would have `rm -f /var/payload/manifests/*-TechPreviewNoUpgrade*.yaml` [3].
* If the manifest has the suffix `_servicemonitor.yaml` in the filename,
  it would be removed too. As a result, the relevant PrometheusRule won't
  exist on the created HCP regardless of FeatureSet. It should not be a problem
  just like the existing one.

The annotations `include.release.openshift.io/self-managed-high-availability: "true"`
and `release.openshift.io/feature-gate: "ClusterUpdateAcceptRisks"` ensure
that it is installed on Standalone clusters only when
`FeatureGate/ClusterUpdateAcceptRisks` is enabled.

[1]. https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-hypershift-release-4.22-periodics-e2e-aks/2030738474943909888

[2]. https://github.com/openshift/cluster-version-operator/blob/c4fb92f94551b8a94f2eb4e1d8c6fdbcbc4aca0f/install/0000_90_cluster-version-operator_02_servicemonitor.yaml#L30

[3]. https://github.com/openshift/hypershift/blob/23fc7eb379fa973ddd1fefd6cc9b4613ec4dc976/control-plane-operator/controllers/hostedcontrolplane/v2/cvo/deployment.go#L205-L241