docs/dev: Update referenced flag
The `--image` does not exist:

```console
$ oc adm release new --image
error: unknown flag: --image
```

The `--to-image` flag can be used instead.