pkg/verify: Test an armored, multi-key keyring
New keyring generated with:

  $ cat redhat.txt simple.txt | gpg --dearmor | gpg --enarmor >combined.txt
  $ sed -i 's/ARMORED FILE/PUBLIC KEY BLOCK/' combined.txt

where the sed avoids:

  $ go test .
  --- FAIL: Test_releaseVerifier_Verify (0.00s)
  		verify_test.go:45: openpgp: invalid argument: expected public or private key block, got: PGP ARMORED FILE
  FAIL
  FAIL		github.com/openshift/cluster-version-operator/pkg/verify				0.014s

because Go's parser requires the well-known labels [1].

[1]: https://github.com/golang/crypto/blob/20be4c3c3ed52bfccdb2d59a412ee1a936d175a7/openpgp/keys.go#L244