pkg/cvo/cvo_scenarios_test: Log wrong-form sync status
Because [1]:

--- FAIL: TestCVO_UpgradeFailedPayloadLoadWithCapsChanges (2.01s)
    cvo_scenarios_test.go:3961: Waiting for condition
    cvo_scenarios_test.go:1919: TestCVO_UpgradeFailedPayloadLoadWithCapsChanges:init: Clearing all status...
    cvo_scenarios_test.go:3961: Waiting for condition
    cvo_scenarios_test.go:3961: Waiting for condition
    cvo_scenarios_test.go:1970: TestCVO_UpgradeFailedPayloadLoadWithCapsChanges:final sync: Clearing all status...
    cvo_scenarios_test.go:3961: Waiting for condition
    cvo_scenarios_test.go:3961: Waiting for condition
    cvo_scenarios_test.go:3961: Waiting for condition
    cvo_scenarios_test.go:3961: Waiting for condition
    cvo_scenarios_test.go:3961: Waiting for condition
    cvo_scenarios_test.go:3961: Waiting for condition
    cvo_scenarios_test.go:3961: Waiting for condition
    cvo_scenarios_test.go:3961: Waiting for condition
    cvo_scenarios_test.go:3961: Waiting for condition
    cvo_scenarios_test.go:3964: saw too many sync events of the wrong form

is not a lot to go on, and scrolling up to find messages like:

  I1025 19:26:40.752141   14616 status.go:170] Synchronizing status errs=field.ErrorList(nil) status=&cvo.SyncWorkerStatus{Generation:1, Failure:error(nil), Done:0, Total:1, Completed:0, Reconciling:false, Initial:false, VersionHash:"Y9500_0QNis=", Architecture:"amd64", LastProgress:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Actual:v1.Release{Version:"1.0.1-abc", Image:"image/image:1", URL:"https://example.com/v1.0.1-abc", Channels:[]string(nil)}, Verified:false, loadPayloadStatus:cvo.LoadPayloadStatus{Step:"VerifyPayloadVersion", Message:"Verifying payload failed version=\"1.0.0-abc\" image=\"image/image:0\" failure=release image version 1.0.1-abc does not match the expected upstream version 1.0.0-abc", AcceptedRisks:"", Failure:(*errors.errorString)(0xc00047e560), Update:v1.Update{Version:"1.0.0-abc", Image:"image/image:0", Force:false}, Verified:false, Local:false, LastTransitionTime:time.Time{wall:0xc14678dc2cd400de, ext:2075310397, loc:(*time.Location)(0x3099160)}}, CapabilitiesStatus:cvo.CapabilityStatus{Status:v1.ClusterVersionCapabilitiesStatus{EnabledCapabilities:[]v1.ClusterVersionCapability{"baremetal", "marketplace"}, KnownCapabilities:[]v1.ClusterVersionCapability{"CSISnapshot", "Console", "Insights", "Storage", "baremetal", "marketplace", "openshift-samples"}}, ImplicitlyEnabledCaps:[]v1.ClusterVersionCapability(nil)}}
  ...
  I1025 19:26:40.752338   14616 sync_worker.go:658] Sync succeeded, transitioning from Updating to Reconciling
  ...
  I1025 19:26:41.253256   14616 sync_worker.go:637] Previous sync status: &cvo.SyncWorkerStatus{Generation:1, Failure:error(nil), Done:1, Total:1, Completed:2, Reconciling:true, Initial:false, VersionHash:"Y9500_0QNis=", Architecture:"amd64", LastProgress:time.Date(2023, time.October, 25, 19, 26, 40, 751472683, time.Local), Actual:v1.Release{Version:"1.0.1-abc", Image:"image/image:1", URL:"https://example.com/v1.0.1-abc", Channels:[]string(nil)}, Verified:false, loadPayloadStatus:cvo.LoadPayloadStatus{Step:"VerifyPayloadVersion", Message:"Verifying payload failed version=\"1.0.0-abc\" image=\"image/image:0\" failure=release image version 1.0.1-abc does not match the expected upstream version 1.0.0-abc", AcceptedRisks:"", Failure:(*errors.errorString)(0xc00047e560), Update:v1.Update{Version:"1.0.0-abc", Image:"image/image:0", Force:false}, Verified:false, Local:false, LastTransitionTime:time.Time{wall:0xc14678dc2cd400de, ext:2075310397, loc:(*time.Location)(0x3099160)}}, CapabilitiesStatus:cvo.CapabilityStatus{Status:v1.ClusterVersionCapabilitiesStatus{EnabledCapabilities:[]v1.ClusterVersionCapability{"baremetal", "marketplace"}, KnownCapabilities:[]v1.ClusterVersionCapability{"CSISnapshot", "Console", "Insights", "Storage", "baremetal", "marketplace", "openshift-samples"}}, ImplicitlyEnabledCaps:[]v1.ClusterVersionCapability(nil)}}

I'm not entirely clear on how we didn't have a Completed:1 round, but
4.12 is pretty old, and it seems unlikely that we would adjust
sync-worker logic to address anything in that space, so instead I'm
softening the "have I completed?" check to be >=1, and not ==1.

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-version-operator/988/pull-ci-openshift-cluster-version-operator-release-4.12-unit/1717260314141003776