pkg/payload: Skip image-references in Test_cvoManifests/install_dir
Avoid:

  $ go test ./pkg/payload
  ...
  --- FAIL: Test_cvoManifests (0.02s)
      --- FAIL: Test_cvoManifests/install_dir (0.02s)
          render_test.go:355: failed to load manifests: error parsing: error unmarshaling JSON: while decoding JSON: Resource with fields Group: "image.openshift.io" Kind: "ImageStream" Name: "" must contain kubernetes required fields kind and name
  ...

These image-refernces files are helpers for 'oc adm release new ...',
they don't need all the properties set that they'd need to be pushed
into a cluster.