vendor: Bump client-go to v0.18.9
Generated with:

  $ github.com/openshift/client-go@05eb9880269c5ff1696fe20f511f9efa8bbdba0e
  $ go get k8s.io/client-go@v0.18.9
  $ go get k8s.io/apiextensions-apiserver@v0.18.9
  $ go get k8s.io/kube-aggregator@v0.18.9
  $ go mod tidy
  $ go mod vendor
  $ git add -A go.* vendor

using:

  $ go version
  go1.15.2 linux/amd64

To pick up [1] and avoid [2]:

  panic: assignment to entry in nil map

  goroutine 80 [running]:
  k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
    /go/src/github.com/openshift/cluster-version-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x105
  panic(0x163d780, 0x1a61ab0)
    /usr/local/go/src/runtime/panic.go:679 +0x1b2
  k8s.io/client-go/tools/leaderelection/resourcelock.(*ConfigMapLock).Update(0xc0000f6000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /go/src/github.com/openshift/cluster-version-operator/vendor/k8s.io/client-go/tools/leaderelection/resourcelock/configmaplock.go:90 +0x129
  k8s.io/client-go/tools/leaderelection.(*LeaderElector).release(0xc000f56b40, 0x6fc23ac00)
    /go/src/github.com/openshift/cluster-version-operator/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:306 +0xc9
  k8s.io/client-go/tools/leaderelection.(*LeaderElector).renew(0xc000f56b40, 0x1abc1a0, 0xc0004a4180)
    /go/src/github.com/openshift/cluster-version-operator/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:294 +0x166
  k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run(0xc000f56b40, 0x1abc1a0, 0xc0004a4140)
    /go/src/github.com/openshift/cluster-version-operator/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:208 +0x15d
  k8s.io/client-go/tools/leaderelection.RunOrDie(0x1abc1a0, 0xc00030de00, 0x1acbcc0, 0xc0000f6000, 0x14f46b0400, 0xa7a358200, 0x6fc23ac00, 0xc001060f30, 0xc0010baa10, 0x0, ...)
    /go/src/github.com/openshift/cluster-version-operator/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:221 +0x96
  github.com/openshift/cluster-version-operator/pkg/start.(*Options).run.func4(0x1abc1a0, 0xc00030de00, 0xc0000f6000, 0xc000f3ab40, 0xc000099d80, 0x1abc1a0, 0xc00030dd80, 0xc00094b500, 0xc0010ba9d0)
    /go/src/github.com/openshift/cluster-version-operator/pkg/start/start.go:179 +0x1b2
  created by github.com/openshift/cluster-version-operator/pkg/start.(*Options).run
    /go/src/github.com/openshift/cluster-version-operator/pkg/start/start.go:177 +0x3f9

The bump from 0.17 to 0.18 also aligns us with the API-server tooling
for OpenShift 4.5 [3].  The openshift/client-go commit is the current
branch tip [4], and avoids issues like:

  $ go test ./...
  ...
  ../../../../pkg/mod/github.com/openshift/client-go@v0.0.0-20191001081553-3b0e988f8cb0/security/clientset/versioned/typed/security/v1/rangeallocation.go:133:5: not enough arguments in call to c.client.Delete().Resource("rangeallocations").VersionedParams(&listOptions, scheme.ParameterCodec).Timeout(timeout).Body(options).Do
    have ()
    want (context.Context)
  ...

[1]: https://github.com/kubernetes/kubernetes/pull/89909
[2]: https://bugzilla.redhat.com/show_bug.cgi?id=1886600
[3]: https://github.com/openshift/origin/commit/d634a58e38a4df7e15ea59821a528113f940a573
[4]: https://github.com/openshift/client-go/commits/release-4.5