pkg: Check AddEventHandler return error
Addressing [1] and similar:

  pkg/autoupdate/autoupdate.go:73:39: Error return value of `(k8s.io/client-go/tools/cache.SharedInformer).AddEventHandler` is not checked (errcheck)
  	cvInformer.Informer().AddEventHandler(ctrl.eventHandler())
  	                                     ^

In a few cases, this triggered additional plumbing changes to bubble
the errors up the call stack.

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-version-operator/934/pull-ci-openshift-cluster-version-operator-master-lint/1651287295325638656#1:build-log.txt%3A43