pkg: Propagate Release.Architecture
Pass the new property around in all clusters, but only propagate it
out to 'status' in the in-cluster ClusterVersion when the relevant
feature gate is enabled.

I'm dropping the "report an error condition when architecture isn't
set" test-case, because now that a non-Multi Operator.release is
always defaulted to runtime.GOARCH in syncAvailableUpdates, we no
longer have a way to trigger architecture-less Cincinnati requests.

Setting 'Architecture: runtime.GOARCH' in
TestOperator_availableUpdatesSync/if_last_successful_check_time_was_too_recent,_do_nothing
avoids triggering a new request because the CVO thinks the
architecture has changed.  Without that pivot:

  $ go test -run TestOperator_availableUpdatesSync/if_last_successful_check_time_was_too_recent,_do_nothing ./pkg/cvo/
  I1120 11:23:53.053380   24806 cvo.go:731] Started syncing available updates "test/default"
  I1120 11:23:53.057477   24806 availableupdates.go:79] Retrieving available updates again, because the architecture has changed from "" to "amd64"
  I1120 11:23:53.068889   24806 availableupdates.go:398] Update service http://127.0.0.1:46459 could not return available updates: ResponseFailed: unexpected HTTP status: 500 Internal Server Error
  I1120 11:23:53.070095   24806 cvo.go:733] Finished syncing available updates "test/default" (16.782722ms)
  --- FAIL: TestOperator_availableUpdatesSync (0.04s)
      --- FAIL: TestOperator_availableUpdatesSync/if_last_successful_check_time_was_too_recent,_do_nothing (0.04s)
          cvo_test.go:2784: unexpected:   (*cvo.availableUpdates)(
              -   nil,
              +   &{
              +           UpdateService: "http://localhost:8080/graph",
              +           Channel:       "fast",
              +           Architecture:  "amd64",
              +           Condition: v1.ClusterOperatorStatusCondition{
  ...